### ISSUE TITLE
Đã Hoàn Thành - Mời Các Bạn Góp Ý

### ISSUE THREAD

**Issue by huuhoanghcmus** [ntngon8399/FinalProject-P4DS#2]

**Comment by huuhoanghcmus** [comment]
Mời các bạn góp ý ở đây

**Comment by nguyenban** [comment]
Chào các bạn, mình thấy nhóm bạn làm khá đầy đủ yêu cầu và mình chưa thấy điều gì bất hợp lý. Tuy nhiên các bạn nên bổ sung thêm ý nghĩa của việc trả lời câu hỏi nha.

**Comment by Duyvugithub** [comment]
Chào các bạn, mình thấy nhóm bạn còn thiếu file "Kế hoạch làm việc", phần "Nhìn lại quá trình làm đồ án" và phân "Tài liêu tham khảo".
Ở phần "Liệt kê kiểu dữ liệu của các cột" thì cột "neutral" mình nghĩ các bạn nên ép kiểu về bool sẽ hợp lý hơn tại vì cột này chỉ chứa 2 giá trị True/False 
Phần "Khám phá dữ liệu" nhóm bạn còn thiếu "Với mỗi cột có kiểu dữ liệu dạng số (numeric), các giá trị
được phân bố như thế nào?" và "Với mỗi cột có kiểu dữ liệu dạng phân loại (categorical),
các giá trị được phân bố như thế nào?"
